### ISSUE TITLE
Refresh Eclipse JHipster project after bootstrapping process 

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#139]

**Comment by angelozerr** [comment]
This issue is about TM Terminal : how to know that command line has finished the process. I had the same problem with Angular Eclipse where you can execute `ng new`:

 * with wizard: use fill information waited by `ng new` and on the `Finish` button, it open terminal with teh well line command and options. See https://github.com/angelozerr/angular-eclipse/wiki/ngWizards
 * with terminal directly by tapping ng new: https://github.com/angelozerr/angular-eclipse/wiki/ngTerminal#ng-new

The 2 mean to create a project (with wizard which opens a terminal or by tapping directly the comman dline in the terminal) must refresh at the end the eclipse project. To do that, I have hacked terminal to have the capability to tracks 3 events:

 * submit of a command.
 * execute of command.
 * terminate of command.

I have created a gerrit patch for TM Terminal at https://bugs.eclipse.org/bugs/show_bug.cgi?id=496109 but it should be really fantastic if we could work together and give us feedback to host this feature for Photon.

Hope you will be interested.

**Comment by colameo** [comment]
thanks for you comment - will have a look to your patch.

**Comment by angelozerr** [comment]
> thanks for you comment - will have a look to your patch.

@colameo please note my patch is not perfect, it's just an idea and I'm very aware to change anything.
