### ISSUE TITLE
Spring Tool Suite (STS)

### ISSUE THREAD

**Issue by DanielFran** [jhipster/jhipster-ide#146]
Installed jhipster-ide through market in STS latest version (3.9.0) and I am not able to:
- create/update a JDL project (not available)
- visualize a JDL since JDL perspective is not available (no editor recognize .jdl file and PlantUML did not show the UML).

Note: GraphViz is installed, and in PlantUML preferences I see: Installation seems OK. File generation is OK.

**Comment by Rapster** [comment]
Here is the error:

> !ENTRY io.github.jhipster.jdl.ui 4 0 2017-07-23 18:28:47.287
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.github.jhipster.jdl.ui [1070]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.ui.codetemplates.ui
    -> Bundle-SymbolicName: org.eclipse.xtext.ui.codetemplates.ui; bundle-version="2.11.0.v20170130-0818"; singleton:="true"
       org.eclipse.xtext.ui.codetemplates.ui [1085]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.ui.codetemplates; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.ui.codetemplates; bundle-version="2.11.0.v20170130-0818"; singleton:="true"
              org.eclipse.xtext.ui.codetemplates [1084]
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.generator; x-installation:="greedy"; resolution:="optional"
                Unresolved requirement: Require-Bundle: de.itemis.xtext.antlr; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.emf.mwe.utils; bundle-version="1.0.0"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.emf.mwe2.launch; bundle-version="2.2.0"; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.builder
           -> Bundle-SymbolicName: org.eclipse.xtext.builder; bundle-version="2.11.0.v20170130-0818"; singleton:="true"
              org.eclipse.xtext.builder [1077]
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.smap
                  -> Bundle-SymbolicName: org.eclipse.xtext.smap; bundle-version="2.11.0.v20170131-1210"
                     org.eclipse.xtext.smap [1082]
                       No resolution report for the bundle.  Unresolved requirement: Require-Bundle: org.eclipse.xtext.builder
    -> Bundle-SymbolicName: org.eclipse.xtext.builder; bundle-version="2.11.0.v20170130-0818"; singleton:="true"
  Bundle was not resolved because of a uses contraint violation.
  org.osgi.service.resolver.ResolutionException: Uses constraint violation. Unable to resolve resource org.eclipse.xtext.ui.codetemplates [osgi.identity; type="osgi.bundle"; version:Version="2.11.0.v20170130-0818"; osgi.identity="org.eclipse.xtext.ui.codetemplates"; singleton:="true"] because it is exposed to package 'com.google.common.base' from resources com.google.guava [osgi.identity; type="osgi.bundle"; version:Version="15.0.0.v201403281430"; osgi.identity="com.google.guava"] and com.google.guava [osgi.identity; type="osgi.bundle"; version:Version="21.0.0.v20170206-1425"; osgi.identity="com.google.guava"] via two dependency chains.

To fix this issue, you just have to install xtext-eclipse: https://eclipse.org/Xtext/download.html

**Comment by colameo** [comment]
we'll have a look after vacation.

**Comment by colameo** [comment]
Works now with STS 3.9.2.RELEASE and new release 1.3.0 of the JHipster IDE.
Please try and give me a feedback - thanks!
