### ISSUE TITLE
TestFramework missing Cypress

### ISSUE THREAD

**Issue by AleMScof** [jhipster/jhipster-ide#393]
Editing a jdl file through VSCode highlights errors whenever there's cypress as testFramework parameter

**To Reproduce**
1. Go to VSCode
2. Use the below sample jdl file
3. `application {
	config {
		applicationType monolith
		serviceDiscoveryType eureka
		devDatabaseType  h2Disk
		testFrameworks [cypress]
		messageBroker kafka
		cacheProvider ehcache
		websocket spring-websocket
		buildTool maven
		prodDatabaseType mysql
		searchEngine elasticsearch
		clientPackageManager npm
		clientFramework angularX
		authenticationType jwt
		nativeLanguage de
		serverPort 8080
		entitySuffix ZooFoobar
		dtoSuffix DTO
		jwtSecretKey "com.hilpert"
		skipClient false
		packageName info.monahan
		baseName stringtough
		skipUserManagement false
		enableTranslation true
		languages [hi, ru]
		jhiPrefix jhi
		reactive false
		enableSwaggerCodegen true
		skipServer false
		enableHibernateCache true
		useSass false
		clientTheme none
		clientThemeVariant primary
	}
}
`
4. Check the highlighted error.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/29773796/171372784-6bae9682-4f8b-4e0e-b841-ff710abaffe4.png">

**Expected behaviour**
Cypress should be allowed as a parameter

**Desktop (please complete the following information):**
 - OS: MacOs Monterey 12.3.1
 - VSCode 1.67.2

**Comment by colameo** [comment]
This is because the [jh base repo](https://github.com/jhipster/jhipster-base) was not updated when the above option was introduced. More specifically, the JSON file [JDLApplicationOptions.json](https://github.com/jhipster/jhipster-base/blob/main/src/JDLApplicationOptions.json) must also contain an options definition for Cypress. Can you please file an issue [there](https://github.com/jhipster/jhipster-base) as well?
